mpv is ready
possum64team/PossumPipe pull request #3
Opened 2021-04-27 13:28 UTC by ura43

The thing is now ready to be embedded into qt. Its embedded into qt as is, but not our interface, so we could theoretically ship as is, but embedding this into our UI properly would be ideal. Don't forget our target is May first

2021-04-29 00:12 UTC, natis1 commented on main.py
> +                vo='x11', # You may not need this
vo='gpu' for sure. definitely don't use x11.

2021-05-01 01:57 UTC, dmnightshade commented
[err.log](https://github.com/possum64team/PossumPipe/files/6408731/err.log)
Currently getting this when I try and run your code.

2021-05-01 05:35 UTC, dmnightshade commented
Debug code crashing program.

2021-05-01 05:41 UTC, dmnightshade requested changes
needs debug code disabled.

2021-05-03 05:00 UTC, ura43 commented
Disabled logging and changed vo to gpu

2021-05-03 05:55 UTC, dmnightshade approved these changes
Change is good

2021-05-11 01:37 UTC, merged